### ISSUE TITLE
Is it possible to use this repo to run ETC client?

### ISSUE THREAD

**Issue by alexqrid** [ETCCooperative/erigon#110]
Hi! Is this repo actual and is it still possible to run Erigon client for Ethereum Classic?

**Comment by alexqrid** [comment]
cc @meowsbits

**Comment by meowsbits** [comment]
Well that's the idea anyways, but I and others (#67) have had a hard time getting it to actually sync all the way to the head. Please feel free to take it for a spin if you want. I'd be eager to hear if it works for you.

**Comment by alexqrid** [comment]
Thanks for the answer. Will try it, and report if it works.

**Comment by meowsbits** [comment]
Following up here with a recent (re-)discovery. 

While running core-geth, I noticed one of the first peers I connected with was an `erigon`.

- `0x7097d9b19f814ae058b6d5e41bf0c683986811ffc926af2f18cfc51e53639981` is block [18,738,536](https://etc.blockscout.com/block/0x7097d9b19f814ae058b6d5e41bf0c683986811ffc926af2f18cfc51e53639981), which is current.
- Commit `c760b949[f4]` is from here, around 9 months ago. I've just made a PR from a branch at this version for documentation: https://github.com/ETCCooperative/erigon/pull/111. 

```
> admin.peers
[{
    caps: ["eth/68"],
    enode: "enode://a34f91f4967ceb624575c455b00c718ac22905eb4af1240f6b952e3b0856fe90e845de3bb1f8f4b32bb2e03915b160ee21bad63da5c74f971cde684400be7d4e@157.230.57.47:30304",
    enr: "enr:-Je4QGxNKolRDMlWUAljRKDZX_WV0O089qeAkm-0R1FvDlZWO8RULACqn5un0dPO56ABybBvOMtfHc6xNqJCmnXp2swDg2V0aMfGhH_RuyWAgmlkgnY0gmlwhJ3mOS-Jc2VjcDI1NmsxoQKjT5H0lnzrYkV1xFWwDHGKwikF60rxJA9rlS47CFb-kIN0Y3CCdmCDdWRwgnZg",
    id: "d074f8c7697706022b336144f3a82291d2bdfe353c4b80e177ba37a05065f870",
    name: "erigon/v2.38.0-dev-c760b949/linux-amd64/go1.19.5",
    network: {
      inbound: false,
      localAddress: "192.168.1.118:47426",
      remoteAddress: "157.230.57.47:30304",
      static: false,
      trusted: false
    },
    protocols: {
      eth: {
        difficulty: 7.24382008098557e+21,
        forkId: {...},
        head: "0x7097d9b19f814ae058b6d5e41bf0c683986811ffc926af2f18cfc51e53639981",
        version: 68
      }
    }
}]
```

```
git --no-pager show c760b949f4 
commit c760b949f4ba219e59828db1920d38989efa0b60 (erigon-ny/devel+classic)
Merge: 18c637a4f3 f7e58a7964
Author: meowsbits <b5c6@protonmail.com>
Date:   Wed Feb 8 00:17:37 2023 +0000

    Merge remote-tracking branch 'upstream/devel' into devel+classic

```
